/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.Cliente;
import Dados.Dados;
import com.sun.org.apache.bcel.internal.generic.InstructionConstants;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kcfurtado
 */
public class Cadastrar extends javax.swing.JFrame {
    private Dados DAO;
    private Cliente cliente;
    
    public Cadastrar() {
        initComponents();
        DAO = new Dados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        DP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoUsario = new javax.swing.JTextField();
        campoSenha = new javax.swing.JTextField();
        campoConfirmar = new javax.swing.JTextField();
        cmpBI = new javax.swing.JTextField();
        cmpNIF = new javax.swing.JTextField();
        cmpNome = new javax.swing.JTextField();
        cmpPais = new javax.swing.JTextField();
        cmpCidade = new javax.swing.JTextField();
        cmpEmail = new javax.swing.JTextField();
        cmpLocalidade = new javax.swing.JTextField();
        cmpTelefone = new javax.swing.JTextField();
        LGINCAdastrar = new javax.swing.JButton();
        LGINCAncelar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel1.setText("Dados Pessoais");

        jLabel2.setText("Usuário");

        jLabel3.setText("Senha");

        jLabel5.setText("Nome");

        jLabel6.setText("B.I");

        jLabel7.setText("NIF");

        jLabel8.setText("Pais");

        jLabel9.setText("Cidade");

        jLabel10.setText("Localidade");

        jLabel11.setText("Email");

        jLabel12.setText("Telefone");

        jLabel4.setText("Confirmar ");

        campoUsario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsarioActionPerformed(evt);
            }
        });

        cmpBI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpBIActionPerformed(evt);
            }
        });

        cmpNIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpNIFActionPerformed(evt);
            }
        });

        cmpNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpNomeActionPerformed(evt);
            }
        });

        cmpPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpPaisActionPerformed(evt);
            }
        });

        cmpCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpCidadeActionPerformed(evt);
            }
        });

        cmpEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpEmailActionPerformed(evt);
            }
        });

        cmpLocalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpLocalidadeActionPerformed(evt);
            }
        });

        cmpTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpTelefoneActionPerformed(evt);
            }
        });

        LGINCAdastrar.setText("Cadastrar");
        LGINCAdastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LGINCAdastrarActionPerformed(evt);
            }
        });

        LGINCAncelar.setText("Cancelar");
        LGINCAncelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LGINCAncelarActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/logoBLL.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel14.setText("Seja BemVindo á");

        javax.swing.GroupLayout DPLayout = new javax.swing.GroupLayout(DP);
        DP.setLayout(DPLayout);
        DPLayout.setHorizontalGroup(
            DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DPLayout.createSequentialGroup()
                .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DPLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DPLayout.createSequentialGroup()
                                .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(DPLayout.createSequentialGroup()
                                        .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmpNome)
                                            .addComponent(cmpBI)
                                            .addComponent(cmpNIF)
                                            .addComponent(cmpPais, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(LGINCAdastrar))
                                .addGap(18, 18, 18)
                                .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DPLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                        .addComponent(cmpLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(DPLayout.createSequentialGroup()
                                        .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(DPLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(LGINCAncelar)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DPLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cmpCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cmpEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cmpTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(DPLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DPLayout.createSequentialGroup()
                                        .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(campoSenha)
                                            .addComponent(campoConfirmar)
                                            .addComponent(campoUsario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel1)))))
                    .addGroup(DPLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel14)))
                .addContainerGap())
        );
        DPLayout.setVerticalGroup(
            DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DPLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DPLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DPLayout.createSequentialGroup()
                        .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(campoUsario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(campoConfirmar))
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmpBI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(cmpCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(cmpLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmpNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(cmpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmpTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmpPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))))
                .addGap(18, 18, 18)
                .addGroup(DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LGINCAncelar)
                    .addComponent(LGINCAdastrar))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsarioActionPerformed

    private void cmpBIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpBIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpBIActionPerformed

    private void cmpNIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpNIFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpNIFActionPerformed

    private void cmpNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpNomeActionPerformed

    private void cmpPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpPaisActionPerformed

    private void cmpCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpCidadeActionPerformed

    private void cmpEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpEmailActionPerformed

    private void cmpLocalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpLocalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpLocalidadeActionPerformed

    private void cmpTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpTelefoneActionPerformed

    @SuppressWarnings("static-access")
    private void LGINCAncelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LGINCAncelarActionPerformed
       this.hide();
        new Home().setVisible(true);
    }//GEN-LAST:event_LGINCAncelarActionPerformed

    private void LGINCAdastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LGINCAdastrarActionPerformed
            if (validarCampos()) {
                if (campoVazioCliente()) {
                try {
                    if (DAO.inserirCliente(cliente)) {
                        JOptionPane.showMessageDialog(this, "Cliente Cadastrado Com êxito");
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Cadastrar.class.getName()).log(Level.SEVERE, null, ex);
                }
                }           
            }
            else{
               JOptionPane.showMessageDialog(this, "Cliente Cadastrado sem êxito");
               
            }    // TODO add your handling code here:
    }//GEN-LAST:event_LGINCAdastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Cadastrar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DP;
    private javax.swing.JButton LGINCAdastrar;
    private javax.swing.JButton LGINCAncelar;
    private javax.swing.JTextField campoConfirmar;
    private javax.swing.JTextField campoSenha;
    private javax.swing.JTextField campoUsario;
    private javax.swing.JTextField cmpBI;
    private javax.swing.JTextField cmpCidade;
    private javax.swing.JTextField cmpEmail;
    private javax.swing.JTextField cmpLocalidade;
    private javax.swing.JTextField cmpNIF;
    private javax.swing.JTextField cmpNome;
    private javax.swing.JTextField cmpPais;
    private javax.swing.JTextField cmpTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar4;
    // End of variables declaration//GEN-END:variables

public boolean validarCampos(){
    if(campoUsario.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Preencha o compo Usuario");
        campoUsario.requestFocus();
        return false;
    }
    if(campoSenha.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Preencha o compo Senha");
        campoSenha.requestFocus();
        return false;
    }
    if(campoConfirmar.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Preencha o compo Confirmar senha");
        campoConfirmar.requestFocus();
        return false;
    }
    if(cmpBI.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Preencha o compo B.I");
        cmpBI.requestFocus();
        return false;
    }
    if(cmpBI.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Preencha o compo B.I");
        cmpBI.requestFocus();
        return false;
    }
    if(cmpNome.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Preencha o compo Nome");
        cmpNome.requestFocus();
        return false;
    }
    if(cmpNIF.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Preencha o compo NIF");
        cmpNIF.requestFocus();
        return false;
    }
    if(cmpPais.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Preencha o compo Pais");
        cmpPais.requestFocus();
        return false;
    }
    if(cmpCidade.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Preencha o compo Cidade");
        cmpCidade.requestFocus();
        return false;
    }
    if(cmpLocalidade.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Preencha o compo Localidade");
        cmpLocalidade.requestFocus();
        return false;
    }
    if(cmpEmail.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Preencha o compo Email");
        cmpEmail.requestFocus();
        return false;
    }
    if(cmpTelefone.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Preencha o compo Telefone");
        cmpTelefone.requestFocus();
        return false;
    }
    if(campoSenha.getText().equals(campoConfirmar)){
        return true;
    }else{
        JOptionPane.showMessageDialog(this, "Senha e Confirmar Senha não coincidem");
        campoSenha.requestFocus();
        return false;
    } 
}

 public boolean campoVazioCliente(){
       Cliente cliente = new Cliente();
       cliente.setUsuario(campoUsario.getText());
       cliente.setSenha(campoSenha.getText());
       cliente.setConfirmaSenha(campoConfirmar.getText());
       cliente.setBi(Integer.parseInt(cmpBI.getText()));
       cliente.setNome(cmpNome.getText());
       cliente.setNif(Integer.parseInt(cmpNIF.getText()));
       cliente.setPais(cmpPais.getText());
       cliente.setCidade(cmpCidade.getText());
       cliente.setLocalidade(cmpLocalidade.getText());
       cliente.setTelefone(Integer.parseInt(cmpTelefone.getText()));
       return true ;
   }
}
